# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

F2 <- function(U, nvals) {
    .Call(`_RecLinkSurv_F2`, U, nvals)
}

F33 <- function(A, B, nvals) {
    .Call(`_RecLinkSurv_F33`, A, B, nvals)
}

sspaste2 <- function(A) {
    .Call(`_RecLinkSurv_sspaste2`, A)
}

sampleD <- function(S, LLA, LLB, LLM, pi, loglik, D, nmatches, sumRowD, sumColD) {
    .Call(`_RecLinkSurv_sampleD`, S, LLA, LLB, LLM, pi, loglik, D, nmatches, sumRowD, sumColD)
}

sampleNM <- function(X, mu, eta, pTrue) {
    .Call(`_RecLinkSurv_sampleNM`, X, mu, eta, pTrue)
}

sampleNM2 <- function(X, mu, eta, pTrue, n) {
    .Call(`_RecLinkSurv_sampleNM2`, X, mu, eta, pTrue, n)
}

sampleM <- function(A, B, pTrue, mu, eta) {
    .Call(`_RecLinkSurv_sampleM`, A, B, pTrue, mu, eta)
}

left <- function(t, knots) {
    .Call(`_RecLinkSurv_left`, t, knots)
}

dpiecelin <- function(x, w, b) {
    .Call(`_RecLinkSurv_dpiecelin`, x, w, b)
}

Hfunc <- function(t, knots, params) {
    .Call(`_RecLinkSurv_Hfunc`, t, knots, params)
}

hfunc <- function(t, knots, params) {
    .Call(`_RecLinkSurv_hfunc`, t, knots, params)
}

