# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

paste1 <- function(G) {
    .Call('_glmRecordlinkage_paste1', PACKAGE = 'glmRecordlinkage', G)
}

listVals <- function(GX, levs) {
    .Call('_glmRecordlinkage_listVals', PACKAGE = 'glmRecordlinkage', GX, levs)
}

F33 <- function(GA, GB, levs) {
    .Call('_glmRecordlinkage_F33', PACKAGE = 'glmRecordlinkage', GA, GB, levs)
}

sampleD <- function(niter, S, LLA, LLB, LLM, PDX, loglik, D, nmatches, sumRowD, sumColD) {
    .Call('_glmRecordlinkage_sampleD', PACKAGE = 'glmRecordlinkage', niter, S, LLA, LLB, LLM, PDX, loglik, D, nmatches, sumRowD, sumColD)
}

sampleM <- function(GA, GB, pi, mu) {
    .Call('_glmRecordlinkage_sampleM', PACKAGE = 'glmRecordlinkage', GA, GB, pi, mu)
}

sampleNM <- function(GA, pi, mu) {
    .Call('_glmRecordlinkage_sampleNM', PACKAGE = 'glmRecordlinkage', GA, pi, mu)
}

